services:
  backend:
    build:
      context: .
      dockerfile: servers/Dockerfile
    ports:
      - "4000:3000"  # опционально, если хочется прямой доступ
    networks:
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - default
networks:
  default:
    driver: bridge
